# SonarCloud configuration
sonar.projectKey=Mostafa-SAID7_Bella
sonar.organization=mostafa-said7
sonar.projectName=Bella Restaurant
sonar.projectVersion=1.0

# Source code
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/coverage/**

# TypeScript configuration
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.exclusions=**/node_modules/**,**/typings.d.ts

# Coverage
sonar.coverage.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**

# Language
sonar.sourceEncoding=UTF-8